### ISSUE TITLE
Footer not sticking to bottom

### ISSUE THREAD

**Issue by ansh-saini** [ACE-VSIT/acewebsite#1]
### Subject of the issue
When the content is less, the background shrinks and the footer does not stay at the bottom of the website.

### Environment
* Windows 10
* Chrome 90, Firefox 88

### Steps to reproduce
1. Visit http://vipsace.org/events/
2. It happens on every page where the content is less.

### Expected behavior
Footer should stick to the bottom of the website regardless of the content size.

### Actual behavior
![image](https://user-images.githubusercontent.com/32511936/118759545-dd252d00-b88e-11eb-93b8-ca8fabd34f57.png)

### Possible solutions
1. `min-height: 100vh` on the body might do the trick.
2. We can make the content a flex box with direction column and `flex-grow: 1`. So it is always occupying the maximum space.

**Comment by NikhilSharma03** [comment]
Can you assign this issue to me?

**Comment by ansh-saini** [comment]
Sure @NikhilSharma03

**Comment by NikhilSharma03** [comment]
@ansh-les Can you please review #7 PR
