### ISSUE TITLE
Misaligned event card height and weird pagination.

### ISSUE THREAD

**Issue by ansh-saini** [ACE-VSIT/acewebsite#2]
### Subject of the issue
The row of event cards on the [Events Page](http://vipsace.org/events/) has cards of uneven length. They should be equal.
There are some weird  pagination type numbers below the cards. They are unnecessary.

NOTE: The footer alignment is not the scope of this issue. There is separate issue open for that #1 

### Environment
* Windows 10
* Chrome 90, Firefox 88

### Steps to reproduce
1. Visit http://vipsace.org/events/

### Expected behavior
![image](https://user-images.githubusercontent.com/32511936/118760385-540ef580-b890-11eb-8154-77ced39f7159.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/32511936/118759545-dd252d00-b88e-11eb-93b8-ca8fabd34f57.png)

### Possible solutions
1. `display: flex` on the container `height: 100%` on each item might work.

**Comment by ivel6482** [comment]
I would like to contribute

**Comment by ansh-saini** [comment]
Sure. Go ahead @ivel6482

**Comment by ivel6482** [comment]
Hello, I am trying to setup the project locally in Windows 10 but I can't get passed the `python manage.py migrate` step. I have created a `.env` file in the root of the project and have pasted the contents from `.env.example`. This step returns the following error: 
```
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

For what I have researched `SECRET_KEY` is a random string, is this correct?

If that is correct I have a string assigned for `SECRET_KEY` in the `.env` file.

Any help would be appreciated, thank you and have a nice day.

**Comment by ansh-saini** [comment]
Yes, `SECRET_KEY` is a random string. Even the `.env.example` defaults should have worked. Did you restart the server after updating the `.env` file? 
If yes, then can you please send me the contents of your `.env` file?

**Comment by ivel6482** [comment]
I believe the issue is preventing me to start the server. If that's not the case, could you point me to the right direction on how to do that?

Here is my `.env`

```
SECRET_KEY=YJ2ytsEbhv8XjMKEbKz                                                                                        1
CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME

DEBUG=true
DATABASE_URL=postgres://{user}:{secret}@localhost:5432/{dbname}

SELECTION_START_DATE=16/03/2021
SELECTION_END_DATE=23/03/2021 23:59:59
SELECTION_RESULT_DATE=29/03/2021 12:59:59
```

**Comment by ashishpahwa7** [comment]
Setting up environment variable differs in windows OS. You need to supply those values to the PATH system variable and restart the command promt.  

https://www.computerhope.com/issues/ch000549.htm

**Comment by ansh-les** [comment]
Hey @ivel6482. I have successfully replicated your issue on my machine. There seems to be some improper configuration in the project. I will fix it and get back to you on the weekend. (tomorrow)

**Comment by ivel6482** [comment]
Thank you @ansh-les. Appreciate your help

**Comment by ansh-saini** [comment]
Hey @ivel6482. I found the issue was that I was accessing the `get_current_timezone` before initializing the `SECRET_KEY` in the settings. I re-ordered those lines and the issue was fixed. But then a different compatibility issue poped up which caused us to downgrade to from python 3.9 to python 3.8
I have updated the repository and documentation accordingly. You now don't need to go through the hassle of installing `mysqlclient` either.
Please [update your fork](https://gist.github.com/CristinaSolana/1885435) and try again.
