### ISSUE TITLE
[website] Need a way to sort the council member list on hompage

### ISSUE THREAD

**Issue by sameerkumar18** [ACE-VSIT/acewebsite#20]
All council member's profile need to be sorted as per designation.
Example - Srijit's profile should be the first in order. 
https://i.imgur.com/S3xZnrO.jpg

**Comment by srijitcoder** [comment]
Add a priority column in the table and sort according to the priority rank. (less the rank more priority)

**Comment by sameerkumar18** [comment]
Fixed #23

**Comment by GMGOG** [comment]
I have got the idea. for the design and the pictures of the members with the info. A HONEYCOMB structure.
![whatsapp image 2018-12-07 at 10 34 07 am](https://user-images.githubusercontent.com/43651504/49875945-485db000-fe48-11e8-9f92-c9b460a13c39.jpeg)
Something like this.. and when cursor points on a shell of someone it will automatically get zoom like the products on the Flipkart and all. and the info with a larger picture will be pop up. what say..?

**Comment by GMGOG** [comment]
I have got an idea. for the design and the pictures of the members with the info. A HONEYCOMB structure.
![whatsapp image 2018-12-07 at 10 34 07 am](https://user-images.githubusercontent.com/43651504/49875945-485db000-fe48-11e8-9f92-c9b460a13c39.jpeg)
Something like this.. and when cursor points on a shell of someone it will automatically get zoom like the products on the Flipkart and all. and the info with a larger picture will be pop up. what say..?
