### ISSUE TITLE
Misaligned buttons on home page

### ISSUE THREAD

**Issue by ansh-saini** [ACE-VSIT/acewebsite#3]
### Subject of the issue
"Mentor" and "Alumni" buttons are not aligned properly on the home page under the "Our Team" section.

### Environment
* Windows 10
* Chrome 90, Firefox 88

### Steps to reproduce
1. Visit http://vipsace.org/
2. Scroll down to the `Our Team` section
3. Wait 2-3 seconds and while the buttons show up (they have a fade-in animation)

### Expected behavior
Buttons should be center aligned.

### Actual behavior
![image](https://user-images.githubusercontent.com/32511936/118832556-5bf58680-b8de-11eb-8073-d87bfad76f09.png)

**Comment by Tamsauce** [comment]
Has this request been assigned yet?

**Comment by ansh-saini** [comment]
Not yet @Tamsauce. Would you like to work on this?

**Comment by bhaveshkys** [comment]
hi, If no one is assigned to this issue then i would like to work on this.

**Comment by ansh-saini** [comment]
Sure @bhaveshkys. You will need to create some data in your database to properly replicate the issue. Because I noticed that the buttons align properly when there is no data.
