### ISSUE TITLE
Navbar is not transparent when it should be

### ISSUE THREAD

**Issue by ansh-saini** [ACE-VSIT/acewebsite#8]
### Subject of the issue
Navbar is not transparent on initial page load. This is desirable for pages which have no cover image. Like the [projects page](http://vipsace.org/projects/)
Similarly, the transparent on scroll functionality should not be there on the projects page. Refer the gif below to see what's the issue with it. Since there is no background image behind it, the white text blends into the white background and is unreadable.

### Steps to reproduce
1. Visit http://vipsace.org/members/
2. Notice the navbar is white.

### Expected behavior
On pages which have a cover image on top. (home page, events page etc.) the navbar should be transparent on initial load. And when scrolling, it should turn opaque. But this should not happen on pages which don't have a cover. In that case, navbar should remain static.

#### Members Page
![ACE Members — Mozilla Firefox 2021-05-22 16-15-47](https://user-images.githubusercontent.com/32511936/119223888-85e6bd00-bb19-11eb-82cc-93e0f145ce57.gif)

#### Projects Page
![ACE Projects — Mozilla Firefox 2021-05-22 16-23-16](https://user-images.githubusercontent.com/32511936/119224479-36ee5700-bb1c-11eb-8213-0dea9ec62dcd.gif)

**Comment by ChhaviArora1401** [comment]
Can I try solving this?

**Comment by ChhaviArora1401** [comment]
Can I try this?

**Comment by ansh-saini** [comment]
Sure @ChhaviArora1401. Go ahead. Let me know if you need help with possible solutions.

**Comment by ChhaviArora1401** [comment]
Thankyou, Sir.

**Comment by ChhaviArora1401** [comment]
#16 fixes this issue
